name: Sync external docs

on:
  push:
    branches: [main]
#  pull_request: #debug
#    branches: [main]
#  schedule:
#    - cron: "*/15 * * * *"

jobs:
  sync-external-docs:
    name: Sync external docs
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          submodules: true

      - name: Update all submodules to latest versions
        run: |
          # Update submodules.
          git submodule update --remote -- "external"
          # Stop if there are no changes.
          git diff --quiet && exit 0
          git add "external"

      - name: Create Pull Request
        id: cpr
        uses: peter-evans/create-pull-request@v3
        commit-message: Sync external docs
        committer: github-actions[bot]
        author: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>
        signoff: false
        branch: depsbot/sync-external-docs
        delete-branch: true
        title: 'deps: Sync external docs'
        body: |
          Auto-generated PR to sync external git submodule(s).
        labels: |
          automated pr
        draft: false

      - name: Approve Pull Request
        uses: hmarr/auto-approve-action@v2
          with:
            github-token: ${{ secrets.GITHUB_TOKEN }}
            pull-request-number: ${{ steps.cpr.outputs.pull-request-number }}
